In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn import ensemble
from sklearn import tree
import pydotplus

import time
%matplotlib inline

In [2]:
# loading dataset 
hr = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')
hr

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,...,3,80,0,8,2,2,7,7,3,6
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
7,30,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,...,2,80,1,1,2,3,1,0,0,0
8,38,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,...,2,80,0,10,2,3,9,7,1,8
9,36,No,Travel_Rarely,1299,Research & Development,27,3,Medical,1,13,...,2,80,2,17,3,2,7,7,7,7
10,35,No,Travel_Rarely,809,Research & Development,16,3,Medical,1,14,...,3,80,1,6,5,3,5,4,0,3
11,29,No,Travel_Rarely,153,Research & Development,15,2,Life Sciences,1,15,...,4,80,0,10,3,3,9,5,0,8
12,31,No,Travel_Rarely,670,Research & Development,26,1,Life Sciences,1,16,...,4,80,1,5,1,2,5,2,4,3
13,34,No,Travel_Rarely,1346,Research & Development,19,2,Medical,1,18,...,3,80,1,3,2,3,2,2,1,2
14,28,Yes,Travel_Rarely,103,Research & Development,24,3,Life Sciences,1,19,...,2,80,0,6,4,3,4,2,0,3
15,29,No,Travel_Rarely,1389,Research & Development,21,4,Life Sciences,1,20,...,3,80,1,10,1,3,10,9,8,8
16,32,No,Travel_Rarely,334,Research & Development,5,2,Life Sciences,1,21,...,4,80,2,7,5,2,6,2,0,5
17,22,No,Non-Travel,1123,Research & Development,16,2,Medical,1,22,...,2,80,2,1,2,2,1,0,0,0
18,53,No,Travel_Rarely,1219,Sales,2,4,Life Sciences,1,23,...,3,80,0,31,3,3,25,8,3,7
19,38,No,Travel_Rarely,371,Research & Development,2,3,Life Sciences,1,24,...,3,80,0,6,3,3,3,2,1,2
20,24,No,Non-Travel,673,Research & Development,11,2,Other,1,26,...,4,80,1,5,5,2,4,2,1,3
21,36,Yes,Travel_Rarely,1218,Sales,9,4,Life Sciences,1,27,...,2,80,0,10,4,3,5,3,0,3
22,34,No,Travel_Rarely,419,Research & Development,7,4,Life Sciences,1,28,...,3,80,0,13,4,3,12,6,2,11
23,21,No,Travel_Rarely,391,Research & Development,15,2,Life Sciences,1,30,...,4,80,0,0,6,3,0,0,0,0
24,34,Yes,Travel_Rarely,699,Research & Development,6,1,Medical,1,31,...,3,80,0,8,2,3,4,2,1,3
25,53,No,Travel_Rarely,1282,Research & Development,5,3,Other,1,32,...,4,80,1,26,3,2,14,13,4,8
26,32,Yes,Travel_Frequently,1125,Research & Development,16,1,Life Sciences,1,33,...,2,80,0,10,5,3,10,2,6,7
27,42,No,Travel_Rarely,691,Sales,8,4,Marketing,1,35,...,4,80,1,10,2,3,9,7,4,2
28,44,No,Travel_Rarely,477,Research & Development,7,4,Medical,1,36,...,4,80,1,24,4,3,22,6,5,17
29,46,No,Travel_Rarely,705,Sales,2,4,Marketing,1,38,...,4,80,0,22,2,2,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1440,36,No,Travel_Frequently,688,Research & Development,4,2,Life Sciences,1,2025,...,2,80,3,18,3,3,4,2,0,2
1441,56,No,Non-Travel,667,Research & Development,1,4,Life Sciences,1,2026,...,1,80,1,13,2,2,13,12,1,9
1442,29,Yes,Travel_Rarely,1092,Research & Development,1,4,Medical,1,2027,...,2,80,3,4,3,4,2,2,2,2
1443,42,No,Travel_Rarely,300,Research & Development,2,3,Life Sciences,1,2031,...,1,80,0,24,2,2,22,6,4,14
1444,56,Yes,Travel_Rarely,310,Research & Development,7,2,Technical Degree,1,2032,...,4,80,1,14,4,1,10,9,9,8
1445,41,No,Travel_Rarely,582,Research & Development,28,4,Life Sciences,1,2034,...,3,80,1,21,3,3,20,7,0,10
1446,34,No,Travel_Rarely,704,Sales,28,3,Marketing,1,2035,...,4,80,2,8,2,3,8,7,1,7
1447,36,No,Non-Travel,301,Sales,15,4,Marketing,1,2036,...,1,80,1,15,4,2,15,12,11,11
1448,41,No,Travel_Rarely,930,Sales,3,3,Life Sciences,1,2037,...,3,80,1,14,5,3,5,4,0,4
1449,32,No,Travel_Rarely,529,Research & Development,2,3,Technical Degree,1,2038,...,4,80,0,4,4,3,4,2,1,2
1450,35,No,Travel_Rarely,1146,Human Resources,26,4,Life Sciences,1,2040,...,3,80,0,9,2,3,9,0,1,7
1451,38,No,Travel_Rarely,345,Sales,10,2,Life Sciences,1,2041,...,3,80,1,10,1,3,10,7,1,9
1452,50,Yes,Travel_Frequently,878,Sales,1,4,Life Sciences,1,2044,...,4,80,2,12,3,3,6,3,0,1
1453,36,No,Travel_Rarely,1120,Sales,11,4,Marketing,1,2045,...,1,80,1,8,2,2,6,3,0,0
1454,45,No,Travel_Rarely,374,Sales,20,3,Life Sciences,1,2046,...,3,80,0,8,3,3,5,3,0,1
1455,40,No,Travel_Rarely,1322,Research & Development,2,4,Life Sciences,1,2048,...,4,80,0,8,2,3,2,2,2,2
1456,35,No,Travel_Frequently,1199,Research & Development,18,4,Life Sciences,1,2049,...,4,80,2,10,2,4,10,2,0,2
1457,40,No,Travel_Rarely,1194,Research & Development,2,4,Medical,1,2051,...,2,80,3,20,2,3,5,3,0,2
1458,35,No,Travel_Rarely,287,Research & Development,1,4,Life Sciences,1,2052,...,4,80,1,4,5,3,4,3,1,1
1459,29,No,Travel_Rarely,1378,Research & Development,13,2,Other,1,2053,...,1,80,1,10,2,3,4,3,0,3
1460,29,No,Travel_Rarely,468,Research & Development,28,4,Medical,1,2054,...,2,80,0,5,3,1,5,4,0,4
1461,50,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,...,2,80,1,20,3,3,3,2,2,0
1462,39,No,Travel_Rarely,722,Sales,24,1,Marketing,1,2056,...,1,80,1,21,2,2,20,9,9,6
1463,31,No,Non-Travel,325,Research & Development,5,3,Medical,1,2057,...,2,80,0,10,2,3,9,4,1,7
1464,26,No,Travel_Rarely,1167,Sales,5,3,Other,1,2060,...,4,80,0,5,2,3,4,2,0,0
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [3]:
# Exploring the data
print(hr.describe())
correlation_matrix = hr.corr()
print(correlation_matrix)
sns.heatmap(correlation_matrix, vmax=.9, square=True)
plt.show()

               Age    DailyRate  DistanceFromHome    Education  EmployeeCount  \
count  1470.000000  1470.000000       1470.000000  1470.000000         1470.0
mean     36.923810   802.485714          9.192517     2.912925            1.0
std       9.135373   403.509100          8.106864     1.024165            0.0
min      18.000000   102.000000          1.000000     1.000000            1.0
25%      30.000000   465.000000          2.000000     2.000000            1.0
50%      36.000000   802.000000          7.000000     3.000000            1.0
75%      43.000000  1157.000000         14.000000     4.000000            1.0
max      60.000000  1499.000000         29.000000     5.000000            1.0

       EmployeeNumber  EnvironmentSatisfaction   HourlyRate  JobInvolvement  \
count     1470.000000              1470.000000  1470.000000     1470.000000
mean      1024.865306                 2.721769    65.891156        2.729932
std        602.024335                 1.093082    20.329428        0.711561
min          1.000000                 1.000000    30.000000        1.000000
25%        491.250000                 2.000000    48.000000        2.000000
50%       1020.500000                 3.000000    66.000000        3.000000
75%       1555.750000                 4.000000    83.750000        3.000000
max       2068.000000                 4.000000   100.000000        4.000000

          JobLevel          ...           RelationshipSatisfaction  \
count  1470.000000          ...                        1470.000000
mean      2.063946          ...                           2.712245
std       1.106940          ...                           1.081209
min       1.000000          ...                           1.000000
25%       1.000000          ...                           2.000000
50%       2.000000          ...                           3.000000
75%       3.000000          ...                           4.000000
max       5.000000          ...                           4.000000

       StandardHours  StockOptionLevel  TotalWorkingYears  \
count         1470.0       1470.000000        1470.000000
mean            80.0          0.793878          11.279592
std              0.0          0.852077           7.780782
min             80.0          0.000000           0.000000
25%             80.0          0.000000           6.000000
50%             80.0          1.000000          10.000000
75%             80.0          1.000000          15.000000
max             80.0          3.000000          40.000000

       TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
count            1470.000000      1470.000000     1470.000000
mean                2.799320         2.761224        7.008163
std                 1.289271         0.706476        6.126525
min                 0.000000         1.000000        0.000000
25%                 2.000000         2.000000        3.000000
50%                 3.000000         3.000000        5.000000
75%                 3.000000         3.000000        9.000000
max                 6.000000         4.000000       40.000000

       YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager
count         1470.000000              1470.000000           1470.000000
mean             4.229252                 2.187755              4.123129
std              3.623137                 3.222430              3.568136
min              0.000000                 0.000000              0.000000
25%              2.000000                 0.000000              2.000000
50%              3.000000                 1.000000              3.000000
75%              7.000000                 3.000000              7.000000
max             18.000000                15.000000             17.000000

[8 rows x 26 columns]
                               Age  DailyRate  DistanceFromHome  Education  \
Age                       1.000000   0.010661         -0.001686   0.208034
DailyRate                 0.010661   1.000000         -0.004985  -0.016806
DistanceFromHome         -0.001686  -0.004985          1.000000   0.021042
Education                 0.208034  -0.016806          0.021042   1.000000
EmployeeCount                  NaN        NaN               NaN        NaN
EmployeeNumber           -0.010145  -0.050990          0.032916   0.042070
EnvironmentSatisfaction   0.010146   0.018355         -0.016075  -0.027128
HourlyRate                0.024287   0.023381          0.031131   0.016775
JobInvolvement            0.029820   0.046135          0.008783   0.042438
JobLevel                  0.509604   0.002966          0.005303   0.101589
JobSatisfaction          -0.004892   0.030571         -0.003669  -0.011296
MonthlyIncome             0.497855   0.007707         -0.017014   0.094961
MonthlyRate               0.028051  -0.032182          0.027473  -0.026084
NumCompaniesWorked        0.299635   0.038153         -0.029251   0.126317
PercentSalaryHike         0.003634   0.022704          0.040235  -0.011111
PerformanceRating         0.001904   0.000473          0.027110  -0.024539
RelationshipSatisfaction  0.053535   0.007846          0.006557  -0.009118
StandardHours                  NaN        NaN               NaN        NaN
StockOptionLevel          0.037510   0.042143          0.044872   0.018422
TotalWorkingYears         0.680381   0.014515          0.004628   0.148280
TrainingTimesLastYear    -0.019621   0.002453         -0.036942  -0.025100
WorkLifeBalance          -0.021490  -0.037848         -0.026556   0.009819
YearsAtCompany            0.311309  -0.034055          0.009508   0.069114
YearsInCurrentRole        0.212901   0.009932          0.018845   0.060236
YearsSinceLastPromotion   0.216513  -0.033229          0.010029   0.054254
YearsWithCurrManager      0.202089  -0.026363          0.014406   0.069065

                          EmployeeCount  EmployeeNumber  \
Age                                 NaN       -0.010145
DailyRate                           NaN       -0.050990
DistanceFromHome                    NaN        0.032916
Education                           NaN        0.042070
EmployeeCount                       NaN             NaN
EmployeeNumber                      NaN        1.000000
EnvironmentSatisfaction             NaN        0.017621
HourlyRate                          NaN        0.035179
JobInvolvement                      NaN       -0.006888
JobLevel                            NaN       -0.018519
JobSatisfaction                     NaN       -0.046247
MonthlyIncome                       NaN       -0.014829
MonthlyRate                         NaN        0.012648
NumCompaniesWorked                  NaN       -0.001251
PercentSalaryHike                   NaN       -0.012944
PerformanceRating                   NaN       -0.020359
RelationshipSatisfaction            NaN       -0.069861
StandardHours                       NaN             NaN
StockOptionLevel                    NaN        0.062227
TotalWorkingYears                   NaN       -0.014365
TrainingTimesLastYear               NaN        0.023603
WorkLifeBalance                     NaN        0.010309
YearsAtCompany                      NaN       -0.011240
YearsInCurrentRole                  NaN       -0.008416
YearsSinceLastPromotion             NaN       -0.009019
YearsWithCurrManager                NaN       -0.009197

                          EnvironmentSatisfaction  HourlyRate  JobInvolvement  \
Age                                      0.010146    0.024287        0.029820
DailyRate                                0.018355    0.023381        0.046135
DistanceFromHome                        -0.016075    0.031131        0.008783
Education                               -0.027128    0.016775        0.042438
EmployeeCount                                 NaN         NaN             NaN
EmployeeNumber                           0.017621    0.035179       -0.006888
EnvironmentSatisfaction                  1.000000   -0.049857       -0.008278
HourlyRate                              -0.049857    1.000000        0.042861
JobInvolvement                          -0.008278    0.042861        1.000000
JobLevel                                 0.001212   -0.027853       -0.012630
JobSatisfaction                         -0.006784   -0.071335       -0.021476
MonthlyIncome                           -0.006259   -0.015794       -0.015271
MonthlyRate                              0.037600   -0.015297       -0.016322
NumCompaniesWorked                       0.012594    0.022157        0.015012
PercentSalaryHike                       -0.031701   -0.009062       -0.017205
PerformanceRating                       -0.029548   -0.002172       -0.029071
RelationshipSatisfaction                 0.007665    0.001330        0.034297
StandardHours                                 NaN         NaN             NaN
StockOptionLevel                         0.003432    0.050263        0.021523
TotalWorkingYears                       -0.002693   -0.002334       -0.005533
TrainingTimesLastYear                   -0.019359   -0.008548       -0.015338
WorkLifeBalance                          0.027627   -0.004607       -0.014617
YearsAtCompany                           0.001458   -0.019582       -0.021355
YearsInCurrentRole                       0.018007   -0.024106        0.008717
YearsSinceLastPromotion                  0.016194   -0.026716       -0.024184
YearsWithCurrManager                    -0.004999   -0.020123        0.025976

                          JobLevel          ...           \
Age                       0.509604          ...
DailyRate                 0.002966          ...
DistanceFromHome          0.005303          ...
Education                 0.101589          ...
EmployeeCount                  NaN          ...
EmployeeNumber           -0.018519          ...
EnvironmentSatisfaction   0.001212          ...
HourlyRate               -0.027853          ...
JobInvolvement           -0.012630          ...
JobLevel                  1.000000          ...
JobSatisfaction          -0.001944          ...
MonthlyIncome             0.950300          ...
MonthlyRate               0.039563          ...
NumCompaniesWorked        0.142501          ...
PercentSalaryHike        -0.034730          ...
PerformanceRating        -0.021222          ...
RelationshipSatisfaction  0.021642          ...
StandardHours                  NaN          ...
StockOptionLevel          0.013984          ...
TotalWorkingYears         0.782208          ...
TrainingTimesLastYear    -0.018191          ...
WorkLifeBalance           0.037818          ...
YearsAtCompany            0.534739          ...
YearsInCurrentRole        0.389447          ...
YearsSinceLastPromotion   0.353885          ...
YearsWithCurrManager      0.375281          ...

                          RelationshipSatisfaction  StandardHours  \
Age                                       0.053535            NaN
DailyRate                                 0.007846            NaN
DistanceFromHome                          0.006557            NaN
Education                                -0.009118            NaN
EmployeeCount                                  NaN            NaN
EmployeeNumber                           -0.069861            NaN
EnvironmentSatisfaction                   0.007665            NaN
HourlyRate                                0.001330            NaN
JobInvolvement                            0.034297            NaN
JobLevel                                  0.021642            NaN
JobSatisfaction                          -0.012454            NaN
MonthlyIncome                             0.025873            NaN
MonthlyRate                              -0.004085            NaN
NumCompaniesWorked                        0.052733            NaN
PercentSalaryHike                        -0.040490            NaN
PerformanceRating                        -0.031351            NaN
RelationshipSatisfaction                  1.000000            NaN
StandardHours                                  NaN            NaN
StockOptionLevel                         -0.045952            NaN
TotalWorkingYears                         0.024054            NaN
TrainingTimesLastYear                     0.002497            NaN
WorkLifeBalance                           0.019604            NaN
YearsAtCompany                            0.019367            NaN
YearsInCurrentRole                       -0.015123            NaN
YearsSinceLastPromotion                   0.033493            NaN
YearsWithCurrManager                     -0.000867            NaN

                          StockOptionLevel  TotalWorkingYears  \
Age                               0.037510           0.680381
DailyRate                         0.042143           0.014515
DistanceFromHome                  0.044872           0.004628
Education                         0.018422           0.148280
EmployeeCount                          NaN                NaN
EmployeeNumber                    0.062227          -0.014365
EnvironmentSatisfaction           0.003432          -0.002693
HourlyRate                        0.050263          -0.002334
JobInvolvement                    0.021523          -0.005533
JobLevel                          0.013984           0.782208
JobSatisfaction                   0.010690          -0.020185
MonthlyIncome                     0.005408           0.772893
MonthlyRate                      -0.034323           0.026442
NumCompaniesWorked                0.030075           0.237639
PercentSalaryHike                 0.007528          -0.020608
PerformanceRating                 0.003506           0.006744
RelationshipSatisfaction         -0.045952           0.024054
StandardHours                          NaN                NaN
StockOptionLevel                  1.000000           0.010136
TotalWorkingYears                 0.010136           1.000000
TrainingTimesLastYear             0.011274          -0.035662
WorkLifeBalance                   0.004129           0.001008
YearsAtCompany                    0.015058           0.628133
YearsInCurrentRole                0.050818           0.460365
YearsSinceLastPromotion           0.014352           0.404858
YearsWithCurrManager              0.024698           0.459188

                          TrainingTimesLastYear  WorkLifeBalance  \
Age                                   -0.019621        -0.021490
DailyRate                              0.002453        -0.037848
DistanceFromHome                      -0.036942        -0.026556
Education                             -0.025100         0.009819
EmployeeCount                               NaN              NaN
EmployeeNumber                         0.023603         0.010309
EnvironmentSatisfaction               -0.019359         0.027627
HourlyRate                            -0.008548        -0.004607
JobInvolvement                        -0.015338        -0.014617
JobLevel                              -0.018191         0.037818
JobSatisfaction                       -0.005779        -0.019459
MonthlyIncome                         -0.021736         0.030683
MonthlyRate                            0.001467         0.007963
NumCompaniesWorked                    -0.066054        -0.008366
PercentSalaryHike                     -0.005221        -0.003280
PerformanceRating                     -0.015579         0.002572
RelationshipSatisfaction               0.002497         0.019604
StandardHours                               NaN              NaN
StockOptionLevel                       0.011274         0.004129
TotalWorkingYears                     -0.035662         0.001008
TrainingTimesLastYear                  1.000000         0.028072
WorkLifeBalance                        0.028072         1.000000
YearsAtCompany                         0.003569         0.012089
YearsInCurrentRole                    -0.005738         0.049856
YearsSinceLastPromotion               -0.002067         0.008941
YearsWithCurrManager                  -0.004096         0.002759

                          YearsAtCompany  YearsInCurrentRole  \
Age                             0.311309            0.212901
DailyRate                      -0.034055            0.009932
DistanceFromHome                0.009508            0.018845
Education                       0.069114            0.060236
EmployeeCount                        NaN                 NaN
EmployeeNumber                 -0.011240           -0.008416
EnvironmentSatisfaction         0.001458            0.018007
HourlyRate                     -0.019582           -0.024106
JobInvolvement                 -0.021355            0.008717
JobLevel                        0.534739            0.389447
JobSatisfaction                -0.003803           -0.002305
MonthlyIncome                   0.514285            0.363818
MonthlyRate                    -0.023655           -0.012815
NumCompaniesWorked             -0.118421           -0.090754
PercentSalaryHike              -0.035991           -0.001520
PerformanceRating               0.003435            0.034986
RelationshipSatisfaction        0.019367           -0.015123
StandardHours                        NaN                 NaN
StockOptionLevel                0.015058            0.050818
TotalWorkingYears               0.628133            0.460365
TrainingTimesLastYear           0.003569           -0.005738
WorkLifeBalance                 0.012089            0.049856
YearsAtCompany                  1.000000            0.758754
YearsInCurrentRole              0.758754            1.000000
YearsSinceLastPromotion         0.618409            0.548056
YearsWithCurrManager            0.769212            0.714365

                          YearsSinceLastPromotion  YearsWithCurrManager
Age                                      0.216513              0.202089
DailyRate                               -0.033229             -0.026363
DistanceFromHome                         0.010029              0.014406
Education                                0.054254              0.069065
EmployeeCount                                 NaN                   NaN
EmployeeNumber                          -0.009019             -0.009197
EnvironmentSatisfaction                  0.016194             -0.004999
HourlyRate                              -0.026716             -0.020123
JobInvolvement                          -0.024184              0.025976
JobLevel                                 0.353885              0.375281
JobSatisfaction                         -0.018214             -0.027656
MonthlyIncome                            0.344978              0.344079
MonthlyRate                              0.001567             -0.036746
NumCompaniesWorked                      -0.036814             -0.110319
PercentSalaryHike                       -0.022154             -0.011985
PerformanceRating                        0.017896              0.022827
RelationshipSatisfaction                 0.033493             -0.000867
StandardHours                                 NaN                   NaN
StockOptionLevel                         0.014352              0.024698
TotalWorkingYears                        0.404858              0.459188
TrainingTimesLastYear                   -0.002067             -0.004096
WorkLifeBalance                          0.008941              0.002759
YearsAtCompany                           0.618409              0.769212
YearsInCurrentRole                       0.548056              0.714365
YearsSinceLastPromotion                  1.000000              0.510224
YearsWithCurrManager                     0.510224              1.000000

[26 rows x 26 columns]

NameError: name 'sns' is not defined

In [4]:
# setting prediction target
# The goal is to predict arribution
Y = hr['Attrition']
hr = hr.drop('Attrition', 1)
Y = pd.get_dummies(Y)
hr = pd.get_dummies(hr)  
Y=Y['Yes']

In [ ]:
# Quick check of data types 
hr.dtypes
Y.dtypes

In [15]:
# PCA for 4 components 
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score

# Use PCA to create new columns 
pca = PCA(n_components=4)
principalComponents = pca.fit_transform(hr)
pca_X = pd.DataFrame(data = principalComponents, 
                     columns = ['principal component 1', 'principal component 2', 'principal component 3', 'principal component 4'])



dt_start_time = time.time()
decision_tree = tree.DecisionTreeClassifier(
    criterion='entropy',
    max_features=4,
    max_depth=4,
)

decision_tree.fit(pca_X, Y)


# Fitting the model 
X = pca_X
decision_tree.fit(X, Y)

# Cross validation with 10% holdout group 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.1, random_state=10)

print('With 10% Holdout: ' + str(decision_tree.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(decision_tree.fit(X, Y).score(X, Y)))

# Cross validating using 10 folds  
from sklearn.model_selection import cross_val_score
print(cross_val_score(decision_tree, X, Y, cv=10))

dt_start_time = time.time()

print ("Decision Tree runtime: {}".format(time.time() - dt_start_time))

With 10% Holdout: 0.7891156462585034
Testing on Sample: 0.8530612244897959
[0.83783784 0.84459459 0.83783784 0.82993197 0.83673469 0.82312925
 0.83673469 0.84931507 0.85616438 0.8630137 ]
Decision Tree runtime: 5.602836608886719e-05

In [7]:
from sklearn import ensemble
# random forest using PCA components
rf_start_time = time.time()
rfc = ensemble.RandomForestClassifier()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.1, random_state=10)
print('With 10% Holdout: ' + str(rfc.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(rfc.fit(X, Y).score(X, Y)))

# Cross validating using 10 folds  
from sklearn.model_selection import cross_val_score
print(cross_val_score(rfc, X, Y, cv=10))


print ("Random Forest runtime: {}".format(time.time() - rf_start_time))

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

With 10% Holdout: 0.7891156462585034
Testing on Sample: 0.9782312925170068
[0.79054054 0.81756757 0.85135135 0.83673469 0.82312925 0.82312925
 0.81632653 0.82191781 0.81506849 0.80136986]
Random Forest runtime: 0.48270487785339355

In [9]:
# selectKbest 
import numpy as np
from sklearn.feature_selection import SelectKBest, f_classif


# Perform feature selection
selector = SelectKBest(f_classif, k=10)
selector.fit(hr,Y)

X_new = selector.transform(hr)
X_new.shape
print(selector.get_support(indices=True))

# Most 10  useful cols 
X_new = selector.transform(hr)
print(X_new.shape)
# Col names 
hr.columns[selector.get_support(indices=True)]

[ 0  9 11 19 23 25 48 51 53 54]
(1470, 10)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [ 4 17 52] are constant.
  UserWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw

Index(['Age', 'JobLevel', 'MonthlyIncome', 'TotalWorkingYears',
       'YearsInCurrentRole', 'YearsWithCurrManager',
       'JobRole_Sales Representative', 'MaritalStatus_Single', 'OverTime_No',
       'OverTime_Yes'],
      dtype='object')

In [10]:
# Make a new dataframe with the stongest features.
selected_features = hr[['Age', 'JobLevel', 'MonthlyIncome','TotalWorkingYears']]

decision_tree.fit(selected_features, Y)

# Cross validation with 10% holdout group 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(selected_features, Y, test_size=0.1, random_state=10)

print('With 10% Holdout: ' + str(decision_tree.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(decision_tree.fit(selected_features, Y).score(selected_features, Y)))

# Cross validating using 10 folds  
from sklearn.model_selection import cross_val_score

print(cross_val_score(decision_tree, selected_features, Y, cv = 10))
print ("Decision Tree runtime: {}".format(time.time() - dt_start_time))

With 10% Holdout: 0.7959183673469388
Testing on Sample: 0.8489795918367347
[0.83108108 0.85135135 0.85135135 0.83673469 0.84353741 0.84353741
 0.82993197 0.82876712 0.85616438 0.84931507]
Decision Tree runtime: 54.70753002166748

In [11]:
# Random forest after using SelectKBest features.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(selected_features, Y, test_size=0.1, random_state=10)

print('With 10% Holdout: ' + str(rfc.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(rfc.fit(selected_features, Y).score(selected_features, Y)))


rf_start_time = time.time()

display(cross_val_score(rfc, selected_features, Y, cv=10))
print ("Random Forest runtime: {}".format(time.time() - rf_start_time))

With 10% Holdout: 0.7278911564625851
Testing on Sample: 0.9782312925170068

array([0.78378378, 0.81756757, 0.83108108, 0.78911565, 0.82993197,
       0.78911565, 0.80272109, 0.80821918, 0.82876712, 0.78082192])

Random Forest runtime: 0.2708899974822998

Now that you've learned about random forests and decision trees let's do an exercise in accuracy. You know that random forests are basically a collection of decision trees. But how do the accuracies of the two models compare?

So here's what you should do. Pick a dataset. It could be one you've worked with before or it could be a new one. Then build the best decision tree you can.

Now try to match that with the simplest random forest you can. For our purposes measure simplicity with runtime. Compare that to the runtime of the decision tree. This is imperfect but just go with it.

Hopefully out of this you'll see the power of random forests, but also their potential costs. Remember, in the real world you won't necessarily be dealing with thousands of rows. It could be millions, billions, or even more.

# Conclusion    
 For this challenge I used the HR dataset from IBM to build a decision tree and random forest model that explore 
attribution. For feature selection I compared 4 componets from  PCA to 4 best features from K-selectbest. I am using run time as a metric of comparison.
    
  After building and evaluating my models, I found that the random forest model was slower and slightly less accurate than the decision tree when using PCA. This trend was not observed in using kselectbest however. The random forest was faster and tested better on the sample. 
    
   In all models there is a large gap between the results of the holdout compared to the results of the sample. This may indicate a flaw. I had trouble with the clasification report and working on adding it in.